---

- name: Add MariaDB 10.1 repo
  yum_repository:
    name: MariaDB
    description: MariaDB yum repo
    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
    enabled: yes

- name: Install prerequest for MariaDB 10.1
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - socat
    - rsync
    - nmap
    - nmap-ncat
    - lsof
    - perl-DBI

- name: Install MariaDB 10.1 and dependencies
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: MariaDB
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MariaDB-compat
    - galera
    - jemalloc
    - MySQL-python

- name: Start and enable MariaDB
  service:
    name: mariadb
    enabled: yes
    state: started

- name: Set root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  notify:
    - Flush privileges

- name: Configure MySql
  template:
    src: .my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host_all: yes
    state: absent
  notify:
    - Flush privileges

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

# Galera Cluster Configuration
- name: stop mariadb
  service:
    name: mariadb
    state: stopped

- name: Edit /etc/my.cnf.d/server.cnf
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_on
    value: true

- name: Edit /etc/my.cnf.d/server.cnf
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_provider
    value: /usr/lib64/galera/libgalera_smm.so

- name: Edit /etc/my.cnf.d/server.cnf
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_cluster_address
    value: "{{ galera_wsrep_cluster_address }}"

- name: Edit /etc/my.cnf.d/server.cnf
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_cluster_name
    value: "{{ galera_wsrep_cluster_name }}"

- name: Edit /etc/my.cnf.d/server.cnf
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_node_address
    value: "{{ galera_wsrep_node_address }}"

- name: Edit /etc/my.cnf.d/server.cnf
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_node_name
    value: "{{ galera_wsrep_node_name }}"

- name: Edit /etc/my.cnf.d/server.cnf
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_sst_method
    value: rsync

- name: Edit /etc/my.cnf.d/server.cnf
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: binlog_format
    value: row

- name: Edit /etc/my.cnf.d/server.cnf
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: default_storage_engine
    value: InnoDB

- name: Edit /etc/my.cnf.d/server.cnf
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: innodb_autoinc_lock_mode
    value: 2

- name: Edit /etc/my.cnf.d/server.cnf
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: bind-address
    value: 0.0.0.0
