---

- name: Add MariaDB 10.1 repo
  yum_repository:
    name: MariaDB
    description: MariaDB yum repo
    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
    enabled: yes

- name: Install prerequest for MariaDB 10.1
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - socat
    - rsync
    #- nmap
    #- nmap-ncat
    #- lsof
    - perl-DBI

- name: Install MariaDB 10.1 and dependencies
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: MariaDB
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MariaDB-compat
    - galera
    - jemalloc
    - MySQL-python
