---

- name: Edit /etc/my.cnf.d/server.cnf (wsrep_on)
  become: yes
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_on
    value: true
  notify:
    - restart mariadb

- name: Edit /etc/my.cnf.d/server.cnf (wsrep_provider)
  become: yes
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_provider
    value: /usr/lib64/galera/libgalera_smm.so
  notify:
    - restart mariadb

- name: Edit /etc/my.cnf.d/server.cnf (wsrep_cluster_address)
  become: yes
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_cluster_address
    value: "{{ galera_wsrep_cluster_address }}"
  notify:
    - restart mariadb

- name: Edit /etc/my.cnf.d/server.cnf (wsrep_cluster_name)
  become: yes
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_cluster_name
    value: "{{ galera_wsrep_cluster_name }}"
  notify:
    - restart mariadb

- name: Edit /etc/my.cnf.d/server.cnf (wsrep_node_address)
  become: yes
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_node_address
    value: "{{ galera_wsrep_node_address }}"
  notify:
    - restart mariadb

- name: Edit /etc/my.cnf.d/server.cnf (wsrep_node_name)
  become: yes
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_node_name
    value: "{{ galera_wsrep_node_name }}"
  notify:
    - restart mariadb

- name: Edit /etc/my.cnf.d/server.cnf (wsrep_sst_method)
  become: yes
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: wsrep_sst_method
    value: rsync
  notify:
    - restart mariadb

- name: Edit /etc/my.cnf.d/server.cnf (binlog_format)
  become: yes
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: binlog_format
    value: row
  notify:
    - restart mariadb

- name: Edit /etc/my.cnf.d/server.cnf (default_storage_engine)
  become: yes
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: default_storage_engine
    value: InnoDB
  notify:
    - restart mariadb

- name: Edit /etc/my.cnf.d/server.cnf (innodb_autoinc_lock_mode)
  become: yes
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: innodb_autoinc_lock_mode
    value: 2
  notify:
    - restart mariadb

- name: Edit /etc/my.cnf.d/server.cnf (bind-address)
  become: yes
  ini_file:
    dest: /etc/my.cnf.d/server.cnf
    section: galera
    option: bind-address
    value: 0.0.0.0
  notify:
    - restart mariadb
